FROM node:20-alpine

# Prisma CLI va build dependencies uchun kerakli paketlarni o'rnatish
RUN apk add --no-cache openssl python3 make g++ netcat-openbsd dos2unix

WORKDIR /app

# package.json va package-lock.json fayllarini ko'chirish
COPY package*.json ./
COPY yarn.lock ./

# prisma papkani ko'chirish (schema.prisma va migrations)
COPY prisma ./prisma/

# Loyiha fayllarini ko'chirish
COPY . .

# Container ichida build va start scripti
RUN dos2unix docker-entrypoint.sh
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 8001

# Container ichida migration va app startini boshqarish uchun entrypoint script
ENTRYPOINT ["docker-entrypoint.sh"]